package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/top.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<link href=\"css/page_top.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<SCRIPT language=JavaScript1.2 src=\"http://localhost:8080/web/js/boot.js\" \r\n");
      out.write("type=text/javascript></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT language=javascript src=\"js/comm.js\" \r\n");
      out.write("type=text/javascript></SCRIPT>\r\n");
      out.write("<DIV class=public_navi>\r\n");
      out.write("<DIV class=logo><IMG height=40  src=\"images/logo.jpg\" width=87></DIV>\r\n");
      out.write("<DIV class=navi_part>\r\n");
      out.write("<DIV class=part_top>\r\n");
      out.write("<UL class=n_main>\r\n");
      out.write("  <LI class=\"m_left\"><A href=\"index.jsp\">首页</A> </LI>\r\n");
      out.write("  <LI class=\"m_right\"><A href=\"book/book.jsp\">图书</A> \r\n");
      out.write("  </LI>\r\n");
      out.write("  <LI class=\"m_right\"><A href=\"elctr/elctronc.jsp\">电子</A> \r\n");
      out.write("  </LI>\r\n");
      out.write("  <LI class=\"m_right\"><A href=\"cloth/clothes.jsp\">服饰</A> \r\n");
      out.write("  </LI>\r\n");
      out.write("  <LI class=\"m_right\"><A href=\"cosmetic/cosmetic.jsp\" >化妆品</A> \r\n");
      out.write("  </LI></UL>\r\n");
      out.write("<UL class=n_help>\r\n");
      out.write("  <LI><A href=\"javascript:AddToShoppingCart(-1);\">购物车</A> </LI>\r\n");
      out.write("  <LI class=help_r><A href=\"register.jsp\" \r\n");
      out.write("  target=_blank>新用户注册</A> </LI></UL></DIV>\r\n");
      out.write("</DIV></DIV>\r\n");
      out.write("<!--页头搜索部分-->\r\n");
      out.write("<SCRIPT src=\"js/search20070319.js\" \r\n");
      out.write("type=text/javascript></SCRIPT>\r\n");
      out.write("<INPUT id=catalognew type=hidden name=catalognew> \r\n");
      out.write("<TABLE class=public_search>\r\n");
      out.write("  <TBODY>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD class=search_left></TD>\r\n");
      out.write("    <TD>\r\n");
      out.write("      <TABLE class=search_middle>\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD vAlign=top><!--关键表格开始-->\r\n");
      out.write("            <TABLE class=search_m_top>\r\n");
      out.write("              <TBODY>\r\n");
      out.write("              <TR>\r\n");
      out.write("                <TD align=center width=\"52%\">\r\n");
      out.write("                  <DIV class=choice_sort>\r\n");
      out.write("                  <H2>请选择分类：</H2>\r\n");
      out.write("                  <UL>\r\n");
      out.write("                    <LI id=li_sort><A id=a_sort onClick=\"sortselect('',this);\" \r\n");
      out.write("                    href=\"#\" name=link_all>所有商品</A> \r\n");
      out.write("</LI>\r\n");
      out.write("                    <LI id=li_sort01><A id=a_sort01 \r\n");
      out.write("                    onclick=\"sortselect('01',this);\" \r\n");
      out.write("                    href=\"#\" name=link_book>图书</A> </LI>\r\n");
      out.write("                    <LI id=li_sort03><A id=a_sort03 \r\n");
      out.write("                    onclick=\"sortselect('03',this);\" \r\n");
      out.write("                    href=\"#\" name=link_music>电子</A> \r\n");
      out.write("</LI>\r\n");
      out.write("                    <LI id=li_sort05><A id=a_sort05 \r\n");
      out.write("                    onclick=\"sortselect('05',this);\" \r\n");
      out.write("                    href=\"#\" name=link_movie>服饰</A> \r\n");
      out.write("</LI>\r\n");
      out.write("                    <LI id=li_sort07><A id=a_sort07 \r\n");
      out.write("                    onclick=\"sortselect('07',this);\" \r\n");
      out.write("                    href=\"#\" name=link_gift>化妆品</A> </LI>\r\n");
      out.write("                    <LI id=li_sortmall><A id=a_sortmall \r\n");
      out.write("                    onclick=\"sortselect('mall',this);\" \r\n");
      out.write("                    href=\"#\" name=link_mall></A> \r\n");
      out.write("                  </LI></UL></DIV></TD>\r\n");
      out.write("                \r\n");
      out.write("                </TR></TBODY></TABLE><!--关键表格结束--></TD></TR>\r\n");
      out.write("        <FORM name=searchform onSubmit=\"return gotosearch();\" \r\n");
      out.write("        action=http://search.dangdang.com/search.aspx method=get>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD align=middle>\r\n");
      out.write("            <DIV class=search_main>\r\n");
      out.write("            <DIV class=main_left>\r\n");
      out.write("            <H1>商品搜索</H1><INPUT class=search_text name=key> \r\n");
      out.write("            <DIV id=div01 style=\"DISPLAY: none\">\r\n");
      out.write("            <UL>\r\n");
      out.write("              <LI class=reduce_l_w><INPUT id=selbook1 type=radio value=1 \r\n");
      out.write("              name=selbook><SPAN onclick=selectradio(this)> 书名</SPAN> </LI>\r\n");
      out.write("              <LI><INPUT id=selbook2 type=radio value=2 name=selbook><SPAN \r\n");
      out.write("              onclick=selectradio(this)> 作者</SPAN> </LI>\r\n");
      out.write("              <LI><INPUT id=selbook3 type=radio value=3 name=selbook><SPAN \r\n");
      out.write("              onclick=selectradio(this)> 出版社</SPAN> </LI>\r\n");
      out.write("              <LI><INPUT id=selbook0 type=radio CHECKED value=0 \r\n");
      out.write("              name=selbook><SPAN onclick=selectradio(this)> 全文</SPAN> \r\n");
      out.write("            </LI></UL></DIV>\r\n");
      out.write("            <DIV id=div03 style=\"DISPLAY: none\">\r\n");
      out.write("            <UL>\r\n");
      out.write("              <LI class=reduce_l_w><INPUT id=selmusic1 type=radio value=1 \r\n");
      out.write("              name=selmusic><SPAN onclick=selectradio(this)> 商品名</SPAN> </LI>\r\n");
      out.write("              <LI><INPUT id=selmusic2 type=radio value=2 name=selmusic><SPAN \r\n");
      out.write("              onclick=selectradio(this)> 品牌</SPAN> </LI>\r\n");
      out.write("              <LI><INPUT id=selmusic3 type=radio value=3 name=selmusic><SPAN \r\n");
      out.write("              onclick=selectradio(this)> 价格</SPAN> </LI>\r\n");
      out.write("              <!--<LI><INPUT id=selmusic4 type=radio value=4 name=selmusic><SPAN \r\n");
      out.write("              onclick=selectradio(this)> 曲目</SPAN> </LI>\r\n");
      out.write("              <LI><INPUT id=selmusic0 type=radio CHECKED value=0 \r\n");
      out.write("              name=selmusic><SPAN onclick=selectradio(this)> 全文</SPAN> -->\r\n");
      out.write("            </LI></UL></DIV>\r\n");
      out.write("            <DIV id=div05 style=\"DISPLAY: none\">\r\n");
      out.write("            <UL>\r\n");
      out.write("              <LI class=reduce_l_w><INPUT id=selmovie1 type=radio value=1 \r\n");
      out.write("              name=selmovie><SPAN onclick=selectradio(this)> 商品名</SPAN> </LI>\r\n");
      out.write("              <LI><INPUT id=selmovie4 type=radio value=4 name=selmovie><SPAN \r\n");
      out.write("              onclick=selectradio(this)> 品牌</SPAN> </LI>\r\n");
      out.write("              <LI><INPUT id=selmovie2 type=radio value=2 name=selmovie><SPAN \r\n");
      out.write("              onclick=selectradio(this)> 价格</SPAN> </LI>\r\n");
      out.write("              <!--<LI><INPUT id=selmovie0 type=radio CHECKED value=0 \r\n");
      out.write("              name=selmovie><SPAN onclick=selectradio(this)> 全文</SPAN> -->\r\n");
      out.write("            </LI></UL></DIV>\r\n");
      out.write("            <DIV id=div07 style=\"DISPLAY: none\">\r\n");
      out.write("            <UL>\r\n");
      out.write("              <LI class=reduce_l_w><INPUT id=selmovie1 type=radio value=1 \r\n");
      out.write("              name=selmovie><SPAN onclick=selectradio(this)> 商品名</SPAN> </LI>\r\n");
      out.write("              <LI><INPUT id=selmovie4 type=radio value=4 name=selmovie><SPAN \r\n");
      out.write("              onclick=selectradio(this)> 品牌</SPAN> </LI>\r\n");
      out.write("              <LI><INPUT id=selmovie2 type=radio value=2 name=selmovie><SPAN \r\n");
      out.write("              onclick=selectradio(this)> 价格</SPAN> </LI>\r\n");
      out.write("              <!--<LI><INPUT id=selmovie0 type=radio CHECKED value=0 \r\n");
      out.write("              name=selmovie><SPAN onclick=selectradio(this)> 全文</SPAN> -->\r\n");
      out.write("            </LI></UL></DIV>\r\n");
      out.write("\t    <INPUT class=search_button id=search_btn_top type=submit value=在所有商品中搜> \r\n");
      out.write("            </DIV>\r\n");
      out.write("            <DIV class=main_right><A \r\n");
      out.write("            href=\"\" \r\n");
      out.write("            name=link_ad_search>高级搜索</A></DIV></DIV></TD></TR><INPUT id=key1 \r\n");
      out.write("        type=hidden name=key1> <INPUT id=key2 type=hidden name=key2> <INPUT \r\n");
      out.write("        id=key3 type=hidden name=key3> <INPUT id=key4 type=hidden name=key4> \r\n");
      out.write("        <INPUT id=key5 type=hidden name=key5> <INPUT id=catalog type=hidden \r\n");
      out.write("        name=catalog> <INPUT id=SearchFromTop type=hidden value=1 \r\n");
      out.write("        name=SearchFromTop> </FORM></TBODY></TABLE></TD>\r\n");
      out.write("<SCRIPT type=text/javascript>\r\n");
      out.write("    showpage('','','');\r\n");
      out.write("</SCRIPT>");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
      out.write("<title>首页</title>\r\n");
      out.write("<LINK href=\"css/default.css\" type=text/css rel=stylesheet>\r\n");
      out.write("<LINK href=\"css/06default.css\" type=text/css rel=stylesheet>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<TABLE id=homepage_main>\r\n");
      out.write("  <TBODY>\r\n");
      out.write("  <TR>\r\n");
      out.write("<TD id=homepage_left width=\"15%\"broder=0 >\r\n");
      out.write("<STYLE type=text/css>.aclass {\r\n");
      out.write("\tCOLOR: #9b9b9b\r\n");
      out.write("}\r\n");
      out.write("#Parent_d .liclass {\r\n");
      out.write("\tPADDING-RIGHT: 4px; PADDING-LEFT: 0px; PADDING-BOTTOM: 0px; WIDTH: auto; PADDING-TOP: 0px\r\n");
      out.write("}\r\n");
      out.write("#Parent_d .ulclassnew {\r\n");
      out.write("\tPADDING-RIGHT: 0px; DISPLAY: block; PADDING-LEFT: 13px; PADDING-BOTTOM: 0px; MARGIN: 0px; WIDTH: 87%; PADDING-TOP: 0px; TEXT-ALIGN: left\r\n");
      out.write("}\r\n");
      out.write("#homepage_left LI {\r\n");
      out.write("\tPADDING-RIGHT: 5px; DISPLAY: inline; PADDING-LEFT: 0px; FONT-WEIGHT: normal; BACKGROUND: url(images/06default_0726_03_4.gif) no-repeat right 50%; FLOAT: left; PADDING-BOTTOM: 0px; MARGIN: 2px 0px 3px 5px; COLOR: #069; WORD-BREAK: keep-all; PADDING-TOP: 0px; WHITE-SPACE: nowrap\r\n");
      out.write("}\r\n");
      out.write("#homepage_left .li1 {\r\n");
      out.write("\tPADDING-RIGHT: 5px; DISPLAY: inline; PADDING-LEFT: 0px; FONT-WEIGHT: normal; BACKGROUND: no-repeat right 50%; FLOAT: left; PADDING-BOTTOM: 0px; MARGIN: 2px 0px 3px 5px; COLOR: #069; WORD-BREAK: keep-all; PADDING-TOP: 0px; WHITE-SPACE: nowrap\r\n");
      out.write("}\r\n");
      out.write("#homepage_left .li2 {\r\n");
      out.write("\tCLEAR: none; PADDING-RIGHT: 5px; DISPLAY: inline; PADDING-LEFT: 0px; FONT-WEIGHT: normal; BACKGROUND: no-repeat right 50%; FLOAT: none; PADDING-BOTTOM: 0px; MARGIN: 2px 0px 3px 5px; COLOR: #069; WORD-BREAK: keep-all; PADDING-TOP: 0px\r\n");
      out.write("}\r\n");
      out.write("#homepage_left .ulclass {\r\n");
      out.write("\tPADDING-RIGHT: 0px; DISPLAY: block; PADDING-LEFT: 0px; PADDING-BOTTOM: 0px; MARGIN: 5px 5px 0px 0px; WIDTH: 96%; PADDING-TOP: 0px; TEXT-ALIGN: left\r\n");
      out.write("}\r\n");
      out.write("#homepage_left TD {\r\n");
      out.write("\tFONT-SIZE: 12px; LINE-HEIGHT: 17px\r\n");
      out.write("}\r\n");
      out.write(".classlistboarder {\r\n");
      out.write("\tBORDER-RIGHT: #cfc7b2 1px solid; PADDING-RIGHT: 10px; BORDER-TOP: #cfc7b2 1px solid; DISPLAY: none; PADDING-LEFT: 10px; Z-INDEX: 1; BACKGROUND: #ffffff; PADDING-BOTTOM: 10px; BORDER-LEFT: #cfc7b2 1px solid; WIDTH: 52px; PADDING-TOP: 10px; BORDER-BOTTOM: #cfc7b2 1px solid; POSITION: absolute\r\n");
      out.write("}\r\n");
      out.write(".font14 {\r\n");
      out.write("\tFONT-SIZE: 14px\r\n");
      out.write("}\r\n");
      out.write("</STYLE>\r\n");
      out.write("<div id=__shangpinfenlei>\r\n");
      out.write("<TABLE cellSpacing=0 cellPadding=0 width=\"100%\"  height=\"100%\" border=0>\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("\t\t\r\n");
      out.write("          <TD width=6><IMG height=21 alt=\"\" \r\n");
      out.write("            src=\"images/left.gif\" width=6></TD>\r\n");
      out.write("          <TD class=colorbai width=\"99%\" \r\n");
      out.write("          background=images/center.gif><SPAN \r\n");
      out.write("            class=font14>用户登录</SPAN></TD>\r\n");
      out.write("          <TD width=7><IMG height=21 alt=\"\" \r\n");
      out.write("            src=\"images/right.gif\" width=6></TD></TR></TBODY></TABLE>\r\n");
      out.write("\t\t\t<TABLE id=Parent_t cellSpacing=0 cellPadding=0 width=\"100%\" border=0 class=\"boardlr\">\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t\t<form action=\"\" method=\"get\" name=\"login\">\r\n");
      out.write("        <TR>\r\n");
      out.write("\t\t<td> <div align=\"center\"> <FONT \r\n");
      out.write("              style=\"FONT-SIZE: 12px\"><FONT \r\n");
      out.write("              color=#cc6600>用户名</FONT></FONT></div></td>\r\n");
      out.write("        <td> \r\n");
      out.write("        <input name=\"user_name\" type=\"text\" class=input id=\"user_name\" style=\"FONT-SIZE: 12px; WIDTH: 110px\" size=\"10\" maxlength=\"18\">\r\n");
      out.write("                </td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t<td> <div align=\"center\"><FONT \r\n");
      out.write("              style=\"FONT-SIZE: 12px\"><FONT \r\n");
      out.write("              color=#cc6600>密码\r\n");
      out.write("\t\t\t  </FONT></FONT></div></td>\r\n");
      out.write("        <td > \r\n");
      out.write("        <input style=\"FONT-SIZE: 12px; WIDTH: 110px\" type=\"password\" name=\"user_pass\" size=\"10\" class=input maxlength=\"18\">\r\n");
      out.write("                </td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t<td colspan=\"2\" nowrap><div align=\"center\">\r\n");
      out.write("        <input type=\"submit\" name=\"Submit\" value=\"登录\">\t\t\t\t\t\t\t \r\n");
      out.write("        <input type=\"reset\" name=\"resetB\" value=\"重填\" onClick=\"\"></div></td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</TABLE>\r\n");
      out.write("<TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD width=6><IMG height=21 alt=\"\" \r\n");
      out.write("            src=\"images/left.gif\" width=6></TD>\r\n");
      out.write("          <TD class=colorbai width=\"99%\" \r\n");
      out.write("          background=images/center.gif><SPAN \r\n");
      out.write("            class=font14>商品分类</SPAN></TD>\r\n");
      out.write("          <TD width=7><IMG height=21 alt=\"\" \r\n");
      out.write("            src=\"images/right.gif\" width=6></TD></TR></TBODY></TABLE>\r\n");
      out.write("\t\t\t<TABLE id=Parent_t cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD class=boardlr style=\"PADDING-LEFT: 5px; PADDING-TOP: 5px\" \r\n");
      out.write("          colSpan=3>\r\n");
      out.write("            <UL class=ulclass>\r\n");
      out.write("              <STRONG style=\"MARGIN-LEFT: 5px\"><A \r\n");
      out.write("              class=colortuhuang \r\n");
      out.write("              href=\"\"><font color=\"#cc6600\">图书</font></A></STRONG> \r\n");
      out.write("            </UL></TD></TR>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD class=boardlr style=\"PADDING-LEFT: 5px; PADDING-TOP: 5px\" \r\n");
      out.write("          colSpan=3>\r\n");
      out.write("            <UL class=ulclass>\r\n");
      out.write("              <STRONG style=\"MARGIN-LEFT: 5px\"><A \r\n");
      out.write("              class=colortuhuang \r\n");
      out.write("              href=\"\"><FONT \r\n");
      out.write("              style=\"FONT-SIZE: 12px\"><FONT \r\n");
      out.write("              color=#cc6600>服饰</FONT></FONT></A></STRONG>\r\n");
      out.write("            </UL></TD></TR>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD class=boardlr style=\"PADDING-LEFT: 5px; PADDING-TOP: 5px\" \r\n");
      out.write("          colSpan=3>\r\n");
      out.write("            <UL class=ulclass>\r\n");
      out.write("              <STRONG style=\"MARGIN-LEFT: 5px\"><A \r\n");
      out.write("              class=colortuhuang \r\n");
      out.write("              href=\"\"><FONT \r\n");
      out.write("              style=\"FONT-SIZE: 12px\"><FONT \r\n");
      out.write("              color=#cc6600>化妆品</FONT></FONT></A></STRONG> </UL></TD></TR>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD class=boardlr style=\"PADDING-LEFT: 5px; PADDING-TOP: 5px\" \r\n");
      out.write("          colSpan=3>\r\n");
      out.write("            <UL class=ulclass>\r\n");
      out.write("              <p><STRONG style=\"MARGIN-LEFT: 5px\"><A \r\n");
      out.write("              class=colortuhuang \r\n");
      out.write("              href=\"\"><FONT \r\n");
      out.write("              style=\"FONT-SIZE: 12px\"><FONT \r\n");
      out.write("              color=#cc6600>电子</FONT></FONT></A></STRONG> </p>\r\n");
      out.write("              <LI><A \r\n");
      out.write("              href=\"\">手机</A> </LI>\r\n");
      out.write("              <LI><A \r\n");
      out.write("              href=\"\">电脑/IT</A> \r\n");
      out.write("              </LI>\r\n");
      out.write("            </UL></TD></TR>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD><IMG height=4 alt=\"\" \r\n");
      out.write("            src=\"images/06default_0726_03_1.gif\" width=4></TD>\r\n");
      out.write("          <TD width=\"99%\" \r\n");
      out.write("          background=images/06default_0726_03_3.gif></TD>\r\n");
      out.write("          <TD><IMG height=4 alt=\"\" \r\n");
      out.write("            src=\"images/06default_0726_03_2.gif\" \r\n");
      out.write("        width=4></TD></TR></TBODY></TABLE></DIV>\r\n");
      out.write("</td>\r\n");
      out.write("<td id=homepage_middle >\r\n");
      out.write("<TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0 >\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("\t\t<TD>\r\n");
      out.write("          <DIV class=adTitle0><A href=\"\"><SPAN \r\n");
      out.write("            class=bigtuhuang><IMG \r\n");
      out.write("            src=\"images/ll060828_lanmu.gif\">商品推荐</SPAN></A>\r\n");
      out.write("\t\t\t</DIV>\r\n");
      out.write("            <TABLE id=UCAdRotate1_dlstRotate__ctl0__ctl0_dlstRotateItems \r\n");
      out.write("            cellSpacing=4 cellPadding=0 border=0>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("</TD></TR></TBODY></TABLE>\r\n");
      out.write("\r\n");
      out.write("<TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0 >\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("\t\t<TD>\r\n");
      out.write("          <DIV class=adTitle0><A href=\"\"><SPAN \r\n");
      out.write("            class=bigtuhuang><IMG \r\n");
      out.write("            src=\"images/ll060828_lanmu.gif\">新品上架</SPAN></A>\r\n");
      out.write("\t\t</DIV>\r\n");
      out.write("            <TABLE id=UCAdRotate1_dlstRotate__ctl0__ctl0_dlstRotateItems \r\n");
      out.write("            cellSpacing=4 cellPadding=0 border=0>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("</TD></TR></TBODY></TABLE>\r\n");
      out.write("\r\n");
      out.write("<TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("\t\t<TD>\r\n");
      out.write("          <DIV class=adTitle0><A href=\"\"><SPAN \r\n");
      out.write("            class=bigtuhuang><IMG \r\n");
      out.write("            src=\"images/ll060828_lanmu.gif\">热销商品</SPAN></A>\r\n");
      out.write("\t\t\t</DIV>\r\n");
      out.write("            <TABLE id=UCAdRotate1_dlstRotate__ctl0__ctl0_dlstRotateItems \r\n");
      out.write("            cellSpacing=4 cellPadding=0 border=0>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("</TD></TR></TBODY></TABLE>\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td id=homepage_right>\r\n");
      out.write("\t  <DIV id=__gonggao>\r\n");
      out.write("      <TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("\t\t<TD class=boardlr style=\"PADDING-LEFT: 9px; HEIGHT: 17px\" \r\n");
      out.write("            align=left><FONT class=colortuhuang \r\n");
      out.write("            style=\"FONT-SIZE: 14px; COLOR: #cc6600\"><STRONG>网站公告</STRONG></FONT></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t</TBODY>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=book>\r\n");
      out.write("      <TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("\t  <TR>\r\n");
      out.write("          <TD class=boardlr style=\"PADDING-LEFT: 9px; HEIGHT: 17px\" \r\n");
      out.write("            align=left><FONT class=colortuhuang \r\n");
      out.write("            style=\"FONT-SIZE: 14px; COLOR: #cc6600\"><STRONG>图书排行榜</STRONG>&nbsp;TOP \r\n");
      out.write("            10</FONT></TD>\r\n");
      out.write("\t  </TR>\r\n");
      out.write("\t  <TR>\r\n");
      out.write("\t  <!--<TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("\t  </TABLE>-->\r\n");
      out.write("\t  </TR>\r\n");
      out.write("\t  </TABLE>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=cloth>\r\n");
      out.write("      <TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD class=boardlr style=\"PADDING-LEFT: 9px; HEIGHT: 17px\" \r\n");
      out.write("            align=left><FONT class=colortuhuang \r\n");
      out.write("            style=\"FONT-SIZE: 14px; COLOR: #cc6600\"><STRONG>服饰排行榜</STRONG>&nbsp;TOP \r\n");
      out.write("            10</FONT></TD>\r\n");
      out.write("        </TR>\r\n");
      out.write("        </TBODY></TABLE>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=__huazhuang>\r\n");
      out.write("\t\t <TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD class=boardlr style=\"PADDING-LEFT: 9px; HEIGHT: 17px\" \r\n");
      out.write("            align=left><FONT class=colortuhuang \r\n");
      out.write("            style=\"FONT-SIZE: 14px; COLOR: #cc6600\"><STRONG>化妆品排行榜</STRONG>&nbsp;TOP \r\n");
      out.write("            10</FONT></TD>\r\n");
      out.write("        </TR>\r\n");
      out.write("        </TBODY></TABLE>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=__dianzi>\r\n");
      out.write("\t\t <TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD class=boardlr style=\"PADDING-LEFT: 9px; HEIGHT: 17px\" \r\n");
      out.write("            align=left><FONT class=colortuhuang \r\n");
      out.write("            style=\"FONT-SIZE: 14px; COLOR: #cc6600\"><STRONG>电子排行榜</STRONG>&nbsp;TOP \r\n");
      out.write("            10</FONT></TD>\r\n");
      out.write("        </TR>\r\n");
      out.write("        </TBODY></TABLE>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
